name: All Tests OK?

on:
  workflow_run:
    workflows:
      - Test* 
      - Test arm_cortex-a9_vfpv3-d16
      - Test x86_64
      - Test mipsel_24kc
      - Test arm_cortex-a15_neon-vfpv4
      - Test aarch64_cortex-a53
      - Test powerpc_464fp
      - Test powerpc_8548
      - Test mips_24kc
      - Test i386_pentium-mmx 
#    branches:
#      - master
    types:
      - completed

jobs:
  checks_OK:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.wait.outputs.result }}
    steps:
      - id: wait
        uses: uplift-ltd/wait-for-workflow-run-action@f6c595f77ce729bedd5bb12d54120732f7f40d8d

#  checks_OK:
#    runs-on: ubuntu-latest
#    needs: checks
#    if: ${{ needs.checks.outputs.result == 'success' }}
#    steps:
#      - run: echo "checks OK"
