on:
  workflow_run:
    workflows: [Test*]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

name: All Tests OK?

on:
  workflow_run:
    workflows:
      - Test*
#    branches:
#      - master
    types:
      - completed

jobs:
  checks:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.wait.outputs.result }}
    steps:
      - id: wait
        uses: uplift-ltd/wait-for-workflow-run-action

  checks_OK?:
    runs-on: ubuntu-latest
    needs: checks
    if: ${{ needs.checks.outputs.result == 'success' }}
    steps:
      - run: echo "checks OK"
